# Jekyll Configuration

# General Settings
# https://jekyllrb.com/docs/configuration/

encoding: utf-8
livereload: true
timezone: Asia/Jakarta

# Build Settings
# https://jekyllrb.com/docs/configuration/options/

include:
  - .htaccess
  - feed.json
  - feed.xml

exclude:
  - .babelrc
  - Makefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - package.json
  - yarn.lock
  - package-lock.json
  - webpack.config.js
  - node_modules
  - Dockerfile
  - docker_compose.yml

whitelist:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-redirect-from
  
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-redirect-from

input_types:
- text
- textarea
- email
- date
- checkbox
- radio
- number
- submit

form_engines:
- cloudcannon
- formspree
- formbucket

# Default Setting
# https://jekyllrb.com/docs/configuration/front-matter-defaults/

base: _feeds/section

collections:
  feeds:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
      type: "feeds"
    values:
      layout: "feeds/section"

# Kramdown Options
# https://kramdown.gettalong.org/options.html
# https://jekyllrb.com/docs/configuration/markdown/

highlighter: rouge
markdown: kramdown

kramdown:
  html_to_native: true
  syntax_highlighter: pygments
  math_engine_opts configuration: mathjax
 
# Custom Headers
# https://jekyllrb.com/docs/configuration/webrick/

# webrick:
#   headers:
#     My-Header: My-Value
#     My-Other-Header: My-Other-Value

# Site Setting
# https://jekyllrb.com/docs/configuration/options/

baseurl: ""
user: chetabahana
organization: marketleader
url: https://chetabahana.github.io
slogan_link: https://www.chetabahana.com/
repository: chetabahana/chetabahana.github.io
json_link: https://chetabahana.github.io/feed.json

# Site Metadata
# https://help.github.com/articles/repository-metadata-on-github-pages/

title: Project Maps
name: Toko Chetabahana | Projek e-Shop di Indonesia
slogan: Chetabahana Project - A Way To Win The Market
description: We are providing an Integrated Open Source Project about The World of e-Commerce.
keywords: chetabahana, projek, toko online, market leader, e-shop, eshop, scripts, open source, github page
impressum: Chetabahana.com | Situs Belanja Jual-Beli Barang dan Promo Aneka Produk Fashion, Busana Muslim, Bayi & Anak-anak, Kecantikan, Tas, Sepatu, Peralatan Rumah Tangga, Elektronik, Makanan & Minuman Kemasan, dll.
disclaimer: The definite key to identify whether you use our concept is when there a kind of development item lies a unified assignment in hexagonal form by six (6) corresponding sets while each sets pick a combination of six (6) routes with a pairing of six (6) to six (6) of all channels.
license: Apache License, Version 2.0
