FROM archlinux:base-devel

LABEL version="1.0.2"
LABEL homepage="https://eq19.github.io/"
LABEL maintainer="eq19 <admin@rq19.com>"
LABEL repository="https://github.com/FeedMapping/deploy"

COPY . .

ENTRYPOINT ["/entrypoint.sh"]
