# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy GitHub Pages with Jekyll Action

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'eQ19'
      - 'Chetabahana'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  github-pages:
    runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initializing
        run: |
          bash .github/workflows/builders/ubuntu/artifact.sh
      - name: Build with Jekyll
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Deploy with Jekyll Action
        uses: helaili/jekyll-action@2.0.5    # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          jekyll_env: github-pages-36
