name: CI

on:
  push:
    branches:
      - 'eQ19'
      - 'Chetabahana'
  pull_request:
      - 'eQ19'

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.matching.outputs.version }}
    steps:
      - uses: actions/checkout@main
