name: CI

on:
  push:
    branches:
      - 'eQ19'
      - 'Chetabahana'
  pull_request:
      - 'eQ19'

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.matching.outputs.version }}
    steps:
      - uses: actions/checkout@main
      - uses: rundocs/checkout@master
      - name: Match the commit message whether to Release!
        run: |
          MESSAGE=$(git log -1 --format="%s")
          if [[ ${MESSAGE} =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "::set-output name=version::${MESSAGE:1}"
          fi
        id: matching
        if: ${{ github.event_name == 'push' }}
